# Generated by Django 4.2.7 on 2023-11-12 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailout',
            options={'permissions': [('deactivate', 'Can deactivate mailouts'), ('view_all', 'Can see all mailouts')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('view_all_messages', 'Can see all messages')], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
